version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
      yarn: 1.22
  build:
    commands:
      - echo Building the Node code...
      - cd $CODEBUILD_SRC_DIR/nodejs-app

  pre_build:
    commands:
      - yarn
  build:
    commands:
      - yarn build
  artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: build
